### ISSUE TITLE
Do not load images

### ISSUE THREAD

**Issue by JarrodCTaylor** [unbill/chrome-drone#9]

**Comment by sweinertjr** [comment]
Cannot use chrome `prefs` to resolve due to https://bugs.chromium.org/p/chromedriver/issues/detail?id=1925

Will punt on this one for now, with contingency plan being to block image requests

**Comment by JarrodCTaylor** [comment]
Closed by: 894201f74750efe9ff2aa8bd403eb3a826a026b2
